Fix double-source-jar [error](https://github.com/google/jimfs/actions/runs/5046931891/jobs/9053197373).
```
[INFO] Building jar: /home/runner/work/jimfs/jimfs/jimfs/target/jimfs-HEAD-SNAPSHOT-sources.jar
Error:  We have duplicated artifacts attached.
...
Error:  Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar-no-fork (attach-sources) on project jimfs: Presumably you have configured maven-source-plugn to execute twice times in your build. You have to configure a classifier for at least on of them. -> [Help 1]
```

Both this and the parent `pom.xml` declare `maven-source-plugin` with subtly different values. I tried modifying them to be the same 2 subtly different values as in Guava, which AFAIK does not have this problem, but that didn't appear to help. Then I tried removing each in turn, and removing this one helped. (Both have been there since the beginning, so something must have changed, despite the WAI closure of [MNG-3119](https://issues.apache.org/jira/browse/MNG-3119), which had initially sounded relevant.)

RELNOTES=n/a
PiperOrigin-RevId: 536746714